apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels: 
    project: roboshop
    env: dev
    component: catalogue
  namespace: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: shanmukhatadisetti/catalogue:v1