apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  labels:
    project: roboshop
    env: dev
    component: mysql
spec:
  selector:
    project: roboshop
    env: dev
    component: mysql
  clusterIP: None
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    project: roboshop
    env: dev
    component: mysql
spec:
  replicas: 2
  serviceName: "mysql-headless"
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: mysql
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: mysql
    spec:
      containers:
      - name: mysql
        image: shanmukhatadisetti/mysql:v1
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ebs-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    project: roboshop
    env: dev
    component: mysql
spec:
  selector:
    project: roboshop
    env: dev
    component: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi